### Welcome to the Python project **Exploring the Evolution of Lego**!

It may not be widely known, but Lego has had its share of ups and downs since its inception in the early 20th century. This includes a particularly rough period in the late 90s. As described in [this article](https://www.businessinsider.com/how-lego-made-a-huge-turnaround-2014-2?r=US&IR=T), Lego was only able to survive due to a successful internal brand (Bionicle) and the introduction of its first licensed series: Star Wars.

You are a Data Analyst at Lego working with the Sales/Customer Success teams.  The Account Executive responsible for the Star Wars partnership has asked for specific information in preparation for their meeting with the Star Wars team. Although Star Wars was critical to the survival of the brand, Lego has since introduced a wide variety of licensed sets over subsequent years. 

Your two questions are as follows:

**1. What percentage of all licensed sets ever released were Star Wars themed?** Save your answer as a variable `the_force` in the form of an integer (e.g. 25).

**2. In which year was Star Wars not the most popular licensed theme (in terms of number of sets released that year)?** Save your answer as a variable `new_era` in the form of an integer (e.g. 2012).

The method through which you approach this question is up to you, but one thing to keep in mind is that the **dataset is not necessarily clean**, and may require the removal rows where there are values missing from _critical_ columns.

Before diving into our analysis though, let's become familiar with the two datasets that will help you with this project:<br><br>

<div style="background-color: #ebf4f7; color: #595959; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style ="font-size:20px"><b>datasets/lego_sets.csv</b></div>
<ul>
    <li><b>set_num:</b> A code that is unique to each set in the dataset. <b><i>This column is critical, and a missing value indicates the set is a duplicate or invalid!</b></i></li>
    <li><b>set_name:</b> A name for every set in the dataset (note that this can be the same for different sets).</li>
    <li><b>year:</b> The date the set was released.</li>
    <li><b>num_parts:</b> The number of parts contained in the set.<b><i> This column is not central to our analyses, so missing values are acceptable.</b></i></li>
        <li><b>theme_name:</b> The name of the sub-theme of the set.</li>
    <li><b>parent_theme:</b> The name of the parent theme the set belongs to. Matches the `name` column of the `parent_themes` csv file.</li>
</ul>
    
<div style ="font-size:20px"><b>datasets/parent_themes.csv</b></div>
<ul>
    <li><b>id:</b> A code that is unique to every theme.</li>
    <li><b>name:</b> The name of the parent theme.</li>
    <li><b>is_licensed:</b> A Boolean column specifying whether the theme is a licensed theme.</li>
</ul>
    </div>

In [1]:
import pandas as pd

In [2]:
lego_sets = pd.read_csv('datasets/lego_sets.csv')
lego_sets.head()

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space